create table fb_targeting_country_group
(
    id            bigint auto_increment comment 'id' primary key,
    unique_key    varchar(32) not null comment 'FB受众唯一Key',
    name          varchar(32) not null comment 'FB受众名称',
    type          varchar(32) not null comment 'FB受众类别(country:国家,city:城市,region区域)',
    country_codes text        not null comment 'FB国家受众编码数组',
    is_worldwide  tinyint(1) default 0 not null comment '是否是全球范围[0:false,1:true]',
    created       datetime default CURRENT_TIMESTAMP null,
    updated       datetime default CURRENT_TIMESTAMP null on update CURRENT_TIMESTAMP
)ENGINE = INNODB COMMENT = 'FB受众国家组表';
-- 唯一索引
ALTER TABLE fb_targeting_country_group
    ADD UNIQUE INDEX uni_key_name(unique_key) USING BTREE;

-- ----------------------------
-- Records of fb_targeting_country_group
-- ----------------------------
INSERT INTO fb_targeting_country_group (id, unique_key, name, type, country_codes, is_worldwide, created, updated) VALUES (1, 'africa', '非洲', 'country_group', '[\"BI\",\"KM\",\"DJ\",\"ER\",\"ET\",\"KE\",\"MG\",\"MW\",\"MU\",\"YT\",\"MZ\",\"RE\",\"RW\",\"SC\",\"SO\",\"SS\",\"UG\",\"TZ\",\"ZM\",\"ZW\",\"AO\",\"CM\",\"CF\",\"TD\",\"CG\",\"CD\",\"GQ\",\"GA\",\"ST\",\"DZ\",\"EG\",\"LY\",\"MA\",\"TN\",\"EH\",\"BW\",\"LS\",\"NA\",\"ZA\",\"SZ\",\"BJ\",\"BF\",\"CV\",\"GM\",\"GH\",\"GN\",\"GW\",\"LR\",\"ML\",\"MR\",\"NE\",\"NG\",\"SH\",\"SN\",\"SL\",\"TG\",\"CI\"]', 0, '2024-07-03 17:30:39', '2024-07-03 17:30:39');
INSERT INTO fb_targeting_country_group (id, unique_key, name, type, country_codes, is_worldwide, created, updated) VALUES (2, 'afta', '东盟自由贸易区', 'country_group', '[\"BN\",\"ID\",\"MY\",\"PH\",\"SG\",\"TH\",\"VN\",\"LA\",\"MM\",\"KH\"]', 0, '2024-07-03 17:30:39', '2024-07-03 17:30:39');
INSERT INTO fb_targeting_country_group (id, unique_key, name, type, country_codes, is_worldwide, created, updated) VALUES (3, 'android_free_store', 'Android 免费商店开放国家/地区', 'country_group', '[\"AF\",\"AL\",\"DZ\",\"AS\",\"AD\",\"AO\",\"AI\",\"AQ\",\"AG\",\"AR\",\"AM\",\"AW\",\"AU\",\"AT\",\"AZ\",\"BH\",\"BD\",\"BB\",\"BY\",\"BE\",\"BZ\",\"BJ\",\"BM\",\"BT\",\"BO\",\"BA\",\"BW\",\"BR\",\"IO\",\"VG\",\"BN\",\"BG\",\"BF\",\"BI\",\"KH\",\"CM\",\"MZ\",\"MM\",\"NA\",\"NR\",\"NP\",\"NL\",\"FJ\",\"NC\",\"NZ\",\"NI\",\"NE\",\"NG\",\"NU\",\"NF\",\"FI\",\"NO\",\"OM\",\"PK\",\"PW\",\"PS\",\"PA\",\"PG\",\"PY\",\"PE\",\"PH\",\"PN\",\"PL\",\"PT\",\"PR\",\"QA\",\"RE\",\"RO\",\"RU\",\"RW\",\"KN\",\"LC\",\"MF\",\"PM\",\"VC\",\"WS\",\"SM\",\"ST\",\"SA\",\"SN\",\"RS\",\"SC\",\"SL\",\"SG\",\"SX\",\"SK\",\"SI\",\"SB\",\"SO\",\"ZA\",\"GS\",\"KR\",\"SS\",\"ES\",\"LK\",\"BL\",\"SH\",\"SR\",\"SJ\",\"SZ\",\"SE\",\"CH\",\"TW\",\"TJ\",\"TZ\",\"TH\",\"BS\",\"TG\",\"TK\",\"TO\",\"TT\",\"TN\",\"TR\",\"TM\",\"TC\",\"TV\",\"UG\",\"UA\",\"AE\",\"GB\",\"UM\",\"US\",\"VI\",\"UY\",\"UZ\",\"VU\",\"VA\",\"VE\",\"VN\",\"WF\",\"EH\",\"YE\",\"ZM\",\"ZW\",\"FR\",\"GF\",\"PF\",\"TF\",\"GA\",\"GM\",\"GE\",\"DE\",\"GH\",\"GI\",\"GR\",\"GL\",\"GD\",\"GP\",\"GU\",\"GT\",\"GG\",\"GN\",\"GW\",\"GY\",\"HT\",\"HN\",\"HK\",\"HU\",\"IS\",\"IN\",\"ID\",\"IQ\",\"IE\",\"IM\",\"IL\",\"IT\",\"CI\",\"JM\",\"JP\",\"JE\",\"JO\",\"KZ\",\"KE\",\"KI\",\"XK\",\"KW\",\"KG\",\"LA\",\"LV\",\"LB\",\"LS\",\"LR\",\"LY\",\"LI\",\"LT\",\"LU\",\"MO\",\"MK\",\"MG\",\"MW\",\"MY\",\"MV\",\"ML\",\"MT\",\"MP\",\"MH\",\"MQ\",\"MR\",\"MU\",\"YT\",\"MX\",\"MD\",\"MC\",\"MN\",\"ME\",\"MS\",\"MA\",\"CA\",\"CV\",\"KY\",\"CF\",\"TD\",\"CL\",\"CN\",\"CX\",\"CC\",\"CO\",\"KM\",\"CG\",\"CD\",\"CK\",\"CR\",\"HR\",\"CW\",\"CY\",\"CZ\",\"DK\",\"DJ\",\"DM\",\"DO\",\"TL\",\"EC\",\"EG\",\"SV\",\"GQ\",\"ER\",\"EE\",\"ET\",\"FK\",\"FO\",\"FM\"]', 0, '2024-07-03 17:30:39', '2024-07-03 17:30:39');
INSERT INTO fb_targeting_country_group (id, unique_key, name, type, country_codes, is_worldwide, created, updated) VALUES (4, 'android_paid_store', 'Android 付费商店开放国家/地区', 'country_group', '[\"AL\",\"DZ\",\"AO\",\"AG\",\"AR\",\"AM\",\"AW\",\"AU\",\"AT\",\"AZ\",\"BH\",\"BD\",\"BY\",\"BE\",\"BZ\",\"BJ\",\"BO\",\"BA\",\"BW\",\"BR\",\"BG\",\"BF\",\"KH\",\"CM\",\"CA\",\"CV\",\"CL\",\"CN\",\"CO\",\"CR\",\"HR\",\"CY\",\"CZ\",\"DK\",\"DO\",\"EC\",\"MK\",\"MY\",\"ML\",\"MT\",\"MU\",\"MX\",\"MD\",\"MA\",\"MZ\",\"NA\",\"NP\",\"NL\",\"LU\",\"NZ\",\"NI\",\"NE\",\"NG\",\"NO\",\"OM\",\"PK\",\"PA\",\"PG\",\"PY\",\"PE\",\"PH\",\"PL\",\"PT\",\"PR\",\"QA\",\"RO\",\"RU\",\"RW\",\"SA\",\"SN\",\"RS\",\"SG\",\"SK\",\"SI\",\"ZA\",\"KR\",\"ES\",\"LK\",\"SE\",\"CH\",\"TW\",\"TJ\",\"TZ\",\"TH\",\"BS\",\"TG\",\"TT\",\"TN\",\"TR\",\"TM\",\"UG\",\"UA\",\"AE\",\"GB\",\"US\",\"UY\",\"UZ\",\"VE\",\"VN\",\"YE\",\"ZM\",\"ZW\",\"EG\",\"SV\",\"EE\",\"FJ\",\"FI\",\"FR\",\"GA\",\"DE\",\"GH\",\"GR\",\"GT\",\"GW\",\"HT\",\"HN\",\"HK\",\"HU\",\"IS\",\"IN\",\"ID\",\"IE\",\"IL\",\"IT\",\"CI\",\"JM\",\"JP\",\"JO\",\"KZ\",\"KE\",\"KW\",\"KG\",\"LA\",\"LV\",\"LB\",\"LI\",\"LT\"]', 0, '2024-07-03 17:30:39', '2024-07-03 17:30:39');
INSERT INTO fb_targeting_country_group (id, unique_key, name, type, country_codes, is_worldwide, created, updated) VALUES (5, 'apec', '亚太经济合作组织', 'country_group', '[\"AU\",\"BN\",\"CA\",\"CL\",\"CN\",\"HK\",\"ID\",\"JP\",\"KR\",\"MY\",\"MX\",\"NZ\",\"PG\",\"PE\",\"PH\",\"RU\",\"SG\",\"TH\",\"US\",\"VN\"]', 0, '2024-07-03 17:30:39', '2024-07-03 17:30:39');
INSERT INTO fb_targeting_country_group (id, unique_key, name, type, country_codes, is_worldwide, created, updated) VALUES (6, 'asia', '亚洲', 'country_group', '[\"KZ\",\"KG\",\"TJ\",\"TM\",\"UZ\",\"CN\",\"HK\",\"MO\",\"TW\",\"JP\",\"MN\",\"KR\",\"AF\",\"BD\",\"BT\",\"IN\",\"MV\",\"NP\",\"PK\",\"LK\",\"BN\",\"KH\",\"ID\",\"LA\",\"MY\",\"MM\",\"PH\",\"SG\",\"TH\",\"TL\",\"VN\",\"AM\",\"AZ\",\"BH\",\"CY\",\"GE\",\"IQ\",\"IL\",\"JO\",\"KW\",\"LB\",\"OM\",\"QA\",\"SA\",\"PS\",\"TR\",\"AE\",\"YE\"]', 0, '2024-07-03 17:30:39', '2024-07-03 17:30:39');
INSERT INTO fb_targeting_country_group (id, unique_key, name, type, country_codes, is_worldwide, created, updated) VALUES (7, 'caribbean', '加勒比地区', 'country_group', '[\"AG\",\"AW\",\"BS\",\"BB\",\"VG\",\"KY\",\"CW\",\"DM\",\"DO\",\"GD\",\"GP\",\"HT\",\"JM\",\"MQ\",\"MS\",\"PR\",\"BL\",\"KN\",\"LC\",\"MF\",\"VC\",\"SX\",\"TT\",\"TC\",\"VI\"]', 0, '2024-07-03 17:30:39', '2024-07-03 17:30:39');
INSERT INTO fb_targeting_country_group (id, unique_key, name, type, country_codes, is_worldwide, created, updated) VALUES (8, 'central_america', '中美洲', 'country_group', '[\"BZ\",\"CR\",\"SV\",\"GT\",\"HN\",\"NI\",\"PA\"]', 0, '2024-07-03 17:30:39', '2024-07-03 17:30:39');
INSERT INTO fb_targeting_country_group (id, unique_key, name, type, country_codes, is_worldwide, created, updated) VALUES (9, 'cisfta', '独立国家联合体自由贸易区', 'country_group', '[\"RU\",\"UA\",\"BY\",\"UZ\",\"MD\",\"AM\",\"KG\",\"KZ\",\"AZ\",\"GE\",\"TJ\"]', 0, '2024-07-03 17:30:39', '2024-07-03 17:30:39');
INSERT INTO fb_targeting_country_group (id, unique_key, name, type, country_codes, is_worldwide, created, updated) VALUES (10, 'eea', '欧洲经济区 (EEA)', 'country_group', '[\"AT\",\"BE\",\"BG\",\"HR\",\"CY\",\"CZ\",\"DK\",\"EE\",\"FI\",\"FR\",\"DE\",\"GR\",\"HU\",\"IE\",\"IT\",\"LV\",\"LT\",\"LU\",\"MT\",\"NL\",\"PL\",\"PT\",\"RO\",\"SK\",\"SI\",\"ES\",\"SE\",\"GB\",\"IS\",\"LI\",\"NO\"]', 0, '2024-07-03 17:30:39', '2024-07-03 17:30:39');
INSERT INTO fb_targeting_country_group (id, unique_key, name, type, country_codes, is_worldwide, created, updated) VALUES (11, 'emerging_markets', '新兴市场', 'country_group', '[\"EG\",\"KE\",\"NG\",\"ZA\",\"CN\",\"ID\",\"IN\",\"MY\",\"PH\",\"TH\",\"VN\",\"PL\",\"RU\",\"TR\",\"AR\",\"BR\",\"CL\",\"CO\",\"MX\",\"AE\",\"SA\"]', 0, '2024-07-03 17:30:39', '2024-07-03 17:30:39');
INSERT INTO fb_targeting_country_group (id, unique_key, name, type, country_codes, is_worldwide, created, updated) VALUES (12, 'europe', '欧洲', 'country_group', '[\"BY\",\"BG\",\"CZ\",\"HU\",\"PL\",\"MD\",\"RO\",\"RU\",\"SK\",\"UA\",\"AX\",\"DK\",\"EE\",\"FO\",\"FI\",\"GG\",\"IS\",\"IE\",\"IM\",\"JE\",\"LV\",\"LT\",\"NO\",\"SJ\",\"SE\",\"GB\",\"AL\",\"AD\",\"BA\",\"HR\",\"GI\",\"GR\",\"VA\",\"IT\",\"MT\",\"ME\",\"PT\",\"SM\",\"RS\",\"SI\",\"ES\",\"MK\",\"AT\",\"BE\",\"FR\",\"DE\",\"LI\",\"LU\",\"MC\",\"NL\",\"CH\",\"XK\"]', 0, '2024-07-03 17:30:39', '2024-07-03 17:30:39');
INSERT INTO fb_targeting_country_group (id, unique_key, name, type, country_codes, is_worldwide, created, updated) VALUES (13, 'gcc', '海湾合作委员会', 'country_group', '[\"BH\",\"KW\",\"OM\",\"QA\",\"SA\",\"AE\"]', 0, '2024-07-03 17:30:39', '2024-07-03 17:30:39');
INSERT INTO fb_targeting_country_group (id, unique_key, name, type, country_codes, is_worldwide, created, updated) VALUES (14, 'itunes_app_store', 'iTunes App Store 开放国家/地区', 'country_group', '[\"AL\",\"DZ\",\"AO\",\"AI\",\"AG\",\"AR\",\"AM\",\"AU\",\"AT\",\"AZ\",\"BH\",\"BB\",\"BY\",\"BE\",\"BZ\",\"BJ\",\"BM\",\"BT\",\"BO\",\"BW\",\"BR\",\"VG\",\"BN\",\"BG\",\"BF\",\"KH\",\"CA\",\"CV\",\"KY\",\"TD\",\"CL\",\"CN\",\"CO\",\"CG\",\"CR\",\"HR\",\"CY\",\"CZ\",\"DK\",\"LU\",\"MO\",\"MK\",\"MG\",\"MW\",\"MY\",\"ML\",\"MT\",\"MR\",\"MU\",\"MX\",\"MD\",\"MN\",\"MS\",\"MZ\",\"NA\",\"NP\",\"NL\",\"NZ\",\"NI\",\"NE\",\"NG\",\"NO\",\"OM\",\"PK\",\"PW\",\"PA\",\"PG\",\"PY\",\"PE\",\"PH\",\"PL\",\"PT\",\"QA\",\"RO\",\"RU\",\"KN\",\"LC\",\"VC\",\"ST\",\"SA\",\"SN\",\"SC\",\"SL\",\"SG\",\"SK\",\"SI\",\"SB\",\"ZA\",\"KR\",\"ES\",\"LK\",\"SR\",\"SZ\",\"SE\",\"CH\",\"TW\",\"TJ\",\"TZ\",\"TH\",\"BS\",\"TT\",\"TN\",\"TR\",\"TM\",\"TC\",\"UG\",\"UA\",\"AE\",\"GB\",\"US\",\"UY\",\"UZ\",\"VE\",\"VN\",\"YE\",\"ZW\",\"DM\",\"DO\",\"EC\",\"EG\",\"SV\",\"EE\",\"FM\",\"FJ\",\"FI\",\"FR\",\"GM\",\"DE\",\"GH\",\"GR\",\"GD\",\"GT\",\"GW\",\"GY\",\"HN\",\"HK\",\"HU\",\"IS\",\"IN\",\"ID\",\"IE\",\"IL\",\"IT\",\"JM\",\"JP\",\"JO\",\"KZ\",\"KE\",\"KW\",\"KG\",\"LA\",\"LV\",\"LB\",\"LR\",\"LT\"]', 0, '2024-07-03 17:30:39', '2024-07-03 17:30:39');
INSERT INTO fb_targeting_country_group (id, unique_key, name, type, country_codes, is_worldwide, created, updated) VALUES (15, 'mercosur', '南方共同市场', 'country_group', '[\"BR\",\"AR\",\"UY\",\"PY\",\"VE\"]', 0, '2024-07-03 17:30:40', '2024-07-03 17:30:40');
INSERT INTO fb_targeting_country_group (id, unique_key, name, type, country_codes, is_worldwide, created, updated) VALUES (16, 'nafta', '北美自由贸易协定', 'country_group', '[\"US\",\"CA\",\"MX\"]', 0, '2024-07-03 17:30:40', '2024-07-03 17:30:40');
INSERT INTO fb_targeting_country_group (id, unique_key, name, type, country_codes, is_worldwide, created, updated) VALUES (17, 'north_america', '北美洲', 'country_group', '[\"BM\",\"CA\",\"GL\",\"MX\",\"PM\",\"US\"]', 0, '2024-07-03 17:30:40', '2024-07-03 17:30:40');
INSERT INTO fb_targeting_country_group (id, unique_key, name, type, country_codes, is_worldwide, created, updated) VALUES (18, 'oceania', '大洋洲', 'country_group', '[\"AU\",\"NZ\",\"NF\",\"FJ\",\"NC\",\"PG\",\"SB\",\"VU\",\"GU\",\"KI\",\"MH\",\"FM\",\"NR\",\"MP\",\"PW\",\"AS\",\"CK\",\"PF\",\"NU\",\"PN\",\"WS\",\"TK\",\"TO\",\"TV\",\"WF\"]', 0, '2024-07-03 17:30:40', '2024-07-03 17:30:40');
INSERT INTO fb_targeting_country_group (id, unique_key, name, type, country_codes, is_worldwide, created, updated) VALUES (19, 'south_america', '南美洲', 'country_group', '[\"AR\",\"BO\",\"BR\",\"CL\",\"CO\",\"EC\",\"FK\",\"GF\",\"GY\",\"PY\",\"PE\",\"SR\",\"UY\",\"VE\"]', 0, '2024-07-03 17:30:40', '2024-07-03 17:30:40');
INSERT INTO fb_targeting_country_group (id, unique_key, name, type, country_codes, is_worldwide, created, updated) VALUES (20, 'worldwide', '全球', 'country_group', '[\"AD\",\"AE\",\"AF\",\"AG\",\"AI\",\"AL\",\"AM\",\"AO\",\"AQ\",\"AR\",\"AS\",\"AT\",\"AU\",\"AW\",\"AX\",\"AZ\",\"BA\",\"BB\",\"BD\",\"BE\",\"BF\",\"BG\",\"BH\",\"BI\",\"BJ\",\"BL\",\"BM\",\"BN\",\"BO\",\"BQ\",\"BR\",\"BS\",\"BT\",\"BW\",\"BY\",\"BZ\",\"CA\",\"CC\",\"CD\",\"CF\",\"CG\",\"CH\",\"CI\",\"CK\",\"CL\",\"CM\",\"CN\",\"CO\",\"CR\",\"CV\",\"CW\",\"CX\",\"CY\",\"CZ\",\"DE\",\"DJ\",\"DK\",\"DM\",\"DO\",\"DZ\",\"EC\",\"EE\",\"EG\",\"EH\",\"ER\",\"ES\",\"ET\",\"MD\",\"ME\",\"MF\",\"MG\",\"MH\",\"MK\",\"ML\",\"MM\",\"MN\",\"MO\",\"MP\",\"MQ\",\"MR\",\"MS\",\"MT\",\"MU\",\"MV\",\"MW\",\"MX\",\"MY\",\"MZ\",\"NA\",\"NC\",\"NE\",\"NF\",\"NG\",\"NI\",\"NL\",\"NO\",\"NP\",\"NR\",\"NU\",\"NZ\",\"OM\",\"PA\",\"PE\",\"PF\",\"PG\",\"PH\",\"PK\",\"PL\",\"PM\",\"PN\",\"PR\",\"PS\",\"PT\",\"PW\",\"PY\",\"QA\",\"RE\",\"RO\",\"RS\",\"RU\",\"RW\",\"SA\",\"SB\",\"SC\",\"SE\",\"SG\",\"SH\",\"SI\",\"SJ\",\"SK\",\"SL\",\"SM\",\"SN\",\"SO\",\"SR\",\"SS\",\"ST\",\"SV\",\"SX\",\"SZ\",\"TC\",\"TD\",\"TF\",\"TG\",\"TH\",\"TJ\",\"TK\",\"TL\",\"TM\",\"TN\",\"TO\",\"TR\",\"TT\",\"TV\",\"TW\",\"TZ\",\"UA\",\"UG\",\"UM\",\"US\",\"UY\",\"UZ\",\"VA\",\"VC\",\"VE\",\"VG\",\"VI\",\"VN\",\"VU\",\"WF\",\"WS\",\"XK\",\"YE\",\"YT\",\"ZA\",\"ZM\",\"ZW\",\"MC\",\"FI\",\"FJ\",\"FK\",\"FM\",\"FO\",\"FR\",\"GA\",\"GB\",\"GD\",\"GE\",\"GF\",\"GG\",\"GH\",\"GI\",\"GL\",\"GM\",\"GN\",\"GP\",\"GQ\",\"GR\",\"GS\",\"GT\",\"GU\",\"GW\",\"GY\",\"HK\",\"HN\",\"HR\",\"HT\",\"HU\",\"ID\",\"IE\",\"IL\",\"IM\",\"IN\",\"IO\",\"IQ\",\"IS\",\"IT\",\"JE\",\"JM\",\"JO\",\"JP\",\"KE\",\"KG\",\"KH\",\"KI\",\"KM\",\"KN\",\"MA\",\"KR\",\"KW\",\"KY\",\"KZ\",\"LA\",\"LB\",\"LC\",\"LI\",\"LK\",\"LR\",\"LS\",\"LT\",\"LU\",\"LV\",\"LY\"]', 1, '2024-07-03 17:30:40', '2024-07-03 17:30:40');
INSERT INTO fb_targeting_country_group (id, unique_key, name, type, country_codes, is_worldwide, created, updated) VALUES (21, 'euro_area', '欧元区', 'country_group', '[\"AT\",\"BE\",\"CY\",\"DE\",\"EE\",\"ES\",\"FI\",\"FR\",\"GR\",\"IE\",\"IT\",\"LT\",\"LU\",\"LV\",\"MT\",\"NL\",\"PT\",\"SI\",\"SK\"]', 0, '2024-07-03 17:30:40', '2024-07-03 17:30:40');



-- ----------------------------
-- Records of fb_targeting_position
-- ----------------------------
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'EH', '西撒哈拉', 'country', 'EH', '西撒哈拉', '', NULL, 0, 0, '2024-07-03 17:28:17', '2024-07-03 17:28:17');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'ER', '厄立特里亚', 'country', 'ER', '厄立特里亚', '', NULL, 1, 0, '2024-07-03 17:28:17', '2024-07-03 17:28:17');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'ES', '西班牙', 'country', 'ES', '西班牙', '', NULL, 1, 1, '2024-07-03 17:28:17', '2024-07-03 17:28:17');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'ET', '埃塞俄比亚', 'country', 'ET', '埃塞俄比亚', '', NULL, 1, 0, '2024-07-03 17:28:17', '2024-07-03 17:28:17');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'FI', '芬兰', 'country', 'FI', '芬兰', '', NULL, 1, 1, '2024-07-03 17:28:17', '2024-07-03 17:28:17');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'FJ', '斐济', 'country', 'FJ', '斐济', '', NULL, 1, 0, '2024-07-03 17:28:18', '2024-07-03 17:28:18');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'FK', '福克兰群岛', 'country', 'FK', '福克兰群岛', '', NULL, 0, 0, '2024-07-03 17:28:18', '2024-07-03 17:28:18');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'FM', '密克罗尼西亚联邦', 'country', 'FM', '密克罗尼西亚联邦', '', NULL, 0, 0, '2024-07-03 17:28:18', '2024-07-03 17:28:18');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'FO', '法罗群岛', 'country', 'FO', '法罗群岛', '', NULL, 1, 0, '2024-07-03 17:28:18', '2024-07-03 17:28:18');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'FR', '法国', 'country', 'FR', '法国', '', NULL, 1, 1, '2024-07-03 17:28:18', '2024-07-03 17:28:18');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'GA', '加蓬', 'country', 'GA', '加蓬', '', NULL, 1, 0, '2024-07-03 17:28:18', '2024-07-03 17:28:18');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'GB', '英国', 'country', 'GB', '英国', '', NULL, 1, 1, '2024-07-03 17:28:18', '2024-07-03 17:28:18');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'GD', '格林纳达', 'country', 'GD', '格林纳达', '', NULL, 1, 0, '2024-07-03 17:28:18', '2024-07-03 17:28:18');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'GE', '格鲁吉亚', 'country', 'GE', '格鲁吉亚', '', NULL, 1, 0, '2024-07-03 17:28:18', '2024-07-03 17:28:18');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'GF', '法属圭亚那', 'country', 'GF', '法属圭亚那', '', NULL, 0, 0, '2024-07-03 17:28:18', '2024-07-03 17:28:18');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'GG', '根西岛', 'country', 'GG', '根西岛', '', NULL, 1, 0, '2024-07-03 17:28:18', '2024-07-03 17:28:18');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'GH', '加纳', 'country', 'GH', '加纳', '', NULL, 1, 0, '2024-07-03 17:28:18', '2024-07-03 17:28:18');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'GI', '直布罗陀', 'country', 'GI', '直布罗陀', '', NULL, 0, 0, '2024-07-03 17:28:18', '2024-07-03 17:28:18');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'GL', '格陵兰', 'country', 'GL', '格陵兰', '', NULL, 1, 0, '2024-07-03 17:28:19', '2024-07-03 17:28:19');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'GM', '冈比亚', 'country', 'GM', '冈比亚', '', NULL, 1, 0, '2024-07-03 17:28:19', '2024-07-03 17:28:19');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'GN', '几内亚', 'country', 'GN', '几内亚', '', NULL, 1, 0, '2024-07-03 17:28:19', '2024-07-03 17:28:19');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'GP', '瓜德罗普岛', 'country', 'GP', '瓜德罗普岛', '', NULL, 0, 0, '2024-07-03 17:28:19', '2024-07-03 17:28:19');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'GQ', '赤道几内亚', 'country', 'GQ', '赤道几内亚', '', NULL, 1, 0, '2024-07-03 17:28:19', '2024-07-03 17:28:19');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'GR', '希腊', 'country', 'GR', '希腊', '', NULL, 1, 1, '2024-07-03 17:28:19', '2024-07-03 17:28:19');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'GS', '南乔治亚岛和南桑威奇群岛', 'country', 'GS', '南乔治亚岛和南桑威奇群岛', '', NULL, 0, 0, '2024-07-03 17:28:19', '2024-07-03 17:28:19');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'GT', '危地马拉', 'country', 'GT', '危地马拉', '', NULL, 1, 1, '2024-07-03 17:28:19', '2024-07-03 17:28:19');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'GU', '关岛', 'country', 'GU', '关岛', '', NULL, 0, 0, '2024-07-03 17:28:19', '2024-07-03 17:28:19');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'GW', '几内亚比绍共和国', 'country', 'GW', '几内亚比绍共和国', '', NULL, 1, 0, '2024-07-03 17:28:19', '2024-07-03 17:28:19');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'GY', '圭亚那', 'country', 'GY', '圭亚那', '', NULL, 1, 0, '2024-07-03 17:28:20', '2024-07-03 17:28:20');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'HK', '香港', 'country', 'HK', '香港', '', NULL, 1, 0, '2024-07-03 17:28:20', '2024-07-03 17:28:20');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'HM', '赫德岛和麦克唐纳群岛', 'country', 'HM', '赫德岛和麦克唐纳群岛', '', NULL, 0, 0, '2024-07-03 17:28:20', '2024-07-03 17:28:20');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'HN', '洪都拉斯', 'country', 'HN', '洪都拉斯', '', NULL, 1, 1, '2024-07-03 17:28:20', '2024-07-03 17:28:20');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'HR', '克罗地亚', 'country', 'HR', '克罗地亚', '', NULL, 1, 0, '2024-07-03 17:28:20', '2024-07-03 17:28:20');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'HT', '海地', 'country', 'HT', '海地', '', NULL, 1, 0, '2024-07-03 17:28:20', '2024-07-03 17:28:20');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'HU', '匈牙利', 'country', 'HU', '匈牙利', '', NULL, 1, 1, '2024-07-03 17:28:20', '2024-07-03 17:28:20');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'ID', '印度尼西亚', 'country', 'ID', '印度尼西亚', '', NULL, 1, 1, '2024-07-03 17:28:20', '2024-07-03 17:28:20');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'IE', '爱尔兰', 'country', 'IE', '爱尔兰', '', NULL, 1, 1, '2024-07-03 17:28:20', '2024-07-03 17:28:20');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'IL', '以色列', 'country', 'IL', '以色列', '', NULL, 1, 1, '2024-07-03 17:28:20', '2024-07-03 17:28:20');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'IM', '马恩岛', 'country', 'IM', '马恩岛', '', NULL, 0, 0, '2024-07-03 17:28:20', '2024-07-03 17:28:20');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'IN', '印度', 'country', 'IN', '印度', '', NULL, 1, 1, '2024-07-03 17:28:21', '2024-07-03 17:28:21');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'IO', '英属印度洋领地', 'country', 'IO', '英属印度洋领地', '', NULL, 0, 0, '2024-07-03 17:28:21', '2024-07-03 17:28:21');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'IQ', '伊拉克', 'country', 'IQ', '伊拉克', '', NULL, 1, 0, '2024-07-03 17:28:21', '2024-07-03 17:28:21');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'IS', '冰岛', 'country', 'IS', '冰岛', '', NULL, 1, 0, '2024-07-03 17:28:21', '2024-07-03 17:28:21');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'IT', '意大利', 'country', 'IT', '意大利', '', NULL, 1, 1, '2024-07-03 17:28:21', '2024-07-03 17:28:21');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'JE', '泽西岛', 'country', 'JE', '泽西岛', '', NULL, 1, 0, '2024-07-03 17:28:21', '2024-07-03 17:28:21');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'JM', '牙买加', 'country', 'JM', '牙买加', '', NULL, 1, 0, '2024-07-03 17:28:21', '2024-07-03 17:28:21');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'JO', '约旦', 'country', 'JO', '约旦', '', NULL, 1, 0, '2024-07-03 17:28:21', '2024-07-03 17:28:21');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'JP', '日本', 'country', 'JP', '日本', '', NULL, 1, 1, '2024-07-03 17:28:21', '2024-07-03 17:28:21');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'KE', '肯尼亚', 'country', 'KE', '肯尼亚', '', NULL, 1, 0, '2024-07-03 17:28:21', '2024-07-03 17:28:21');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'KG', '吉尔吉斯斯坦', 'country', 'KG', '吉尔吉斯斯坦', '', NULL, 1, 0, '2024-07-03 17:28:21', '2024-07-03 17:28:21');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'KH', '柬埔寨', 'country', 'KH', '柬埔寨', '', NULL, 1, 0, '2024-07-03 17:28:21', '2024-07-03 17:28:21');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'KI', '基里巴斯', 'country', 'KI', '基里巴斯', '', NULL, 0, 0, '2024-07-03 17:28:22', '2024-07-03 17:28:22');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'KM', '科摩罗', 'country', 'KM', '科摩罗', '', NULL, 1, 0, '2024-07-03 17:28:22', '2024-07-03 17:28:22');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'KN', '圣基茨和尼维斯', 'country', 'KN', '圣基茨和尼维斯', '', NULL, 0, 0, '2024-07-03 17:28:22', '2024-07-03 17:28:22');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'KR', '韩国', 'country', 'KR', '韩国', '', NULL, 1, 1, '2024-07-03 17:28:22', '2024-07-03 17:28:22');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'KW', '科威特', 'country', 'KW', '科威特', '', NULL, 1, 0, '2024-07-03 17:28:22', '2024-07-03 17:28:22');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'KY', '开曼群岛', 'country', 'KY', '开曼群岛', '', NULL, 1, 0, '2024-07-03 17:28:22', '2024-07-03 17:28:22');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'KZ', '哈萨克斯坦', 'country', 'KZ', '哈萨克斯坦', '', NULL, 1, 0, '2024-07-03 17:28:22', '2024-07-03 17:28:22');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'LA', '老挝', 'country', 'LA', '老挝', '', NULL, 1, 0, '2024-07-03 17:28:22', '2024-07-03 17:28:22');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'LB', '黎巴嫩', 'country', 'LB', '黎巴嫩', '', NULL, 1, 0, '2024-07-03 17:28:22', '2024-07-03 17:28:22');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'LC', '圣卢西亚', 'country', 'LC', '圣卢西亚', '', NULL, 0, 0, '2024-07-03 17:28:22', '2024-07-03 17:28:22');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'LI', '列支敦士登', 'country', 'LI', '列支敦士登', '', NULL, 1, 0, '2024-07-03 17:28:22', '2024-07-03 17:28:22');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'LK', '斯里兰卡', 'country', 'LK', '斯里兰卡', '', NULL, 1, 0, '2024-07-03 17:28:23', '2024-07-03 17:28:23');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'LR', '利比里亚', 'country', 'LR', '利比里亚', '', NULL, 1, 0, '2024-07-03 17:28:23', '2024-07-03 17:28:23');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'LS', '莱索托', 'country', 'LS', '莱索托', '', NULL, 1, 0, '2024-07-03 17:28:23', '2024-07-03 17:28:23');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'LT', '立陶宛', 'country', 'LT', '立陶宛', '', NULL, 1, 0, '2024-07-03 17:28:23', '2024-07-03 17:28:23');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'LU', '卢森堡', 'country', 'LU', '卢森堡', '', NULL, 1, 0, '2024-07-03 17:28:23', '2024-07-03 17:28:23');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'LV', '拉脱维亚', 'country', 'LV', '拉脱维亚', '', NULL, 1, 0, '2024-07-03 17:28:23', '2024-07-03 17:28:23');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'LY', '利比亞', 'country', 'LY', '利比亞', '', NULL, 1, 0, '2024-07-03 17:28:23', '2024-07-03 17:28:23');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'MA', '摩洛哥', 'country', 'MA', '摩洛哥', '', NULL, 1, 0, '2024-07-03 17:28:23', '2024-07-03 17:28:23');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'MC', '摩纳哥', 'country', 'MC', '摩纳哥', '', NULL, 1, 0, '2024-07-03 17:28:23', '2024-07-03 17:28:23');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'MD', '摩尔多瓦', 'country', 'MD', '摩尔多瓦', '', NULL, 1, 0, '2024-07-03 17:28:23', '2024-07-03 17:28:23');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'ME', '黑山共和国', 'country', 'ME', '黑山共和国', '', NULL, 1, 0, '2024-07-03 17:28:23', '2024-07-03 17:28:23');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'MF', '法属圣马丁', 'country', 'MF', '法属圣马丁', '', NULL, 0, 0, '2024-07-03 17:28:23', '2024-07-03 17:28:23');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'MG', '马达加斯加', 'country', 'MG', '马达加斯加', '', NULL, 1, 0, '2024-07-03 17:28:24', '2024-07-03 17:28:24');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'MH', '马绍尔群岛', 'country', 'MH', '马绍尔群岛', '', NULL, 1, 0, '2024-07-03 17:28:24', '2024-07-03 17:28:24');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'MK', '马其顿', 'country', 'MK', '马其顿', '', NULL, 1, 0, '2024-07-03 17:28:24', '2024-07-03 17:28:24');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'ML', '马里', 'country', 'ML', '马里', '', NULL, 1, 0, '2024-07-03 17:28:24', '2024-07-03 17:28:24');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'MM', '缅甸', 'country', 'MM', '缅甸', '', NULL, 0, 0, '2024-07-03 17:28:24', '2024-07-03 17:28:24');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'MN', '蒙古', 'country', 'MN', '蒙古', '', NULL, 1, 0, '2024-07-03 17:28:24', '2024-07-03 17:28:24');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'MO', '澳门', 'country', 'MO', '澳门', '', NULL, 0, 0, '2024-07-03 17:28:24', '2024-07-03 17:28:24');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'MP', '北马里亚纳群岛', 'country', 'MP', '北马里亚纳群岛', '', NULL, 0, 0, '2024-07-03 17:28:24', '2024-07-03 17:28:24');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'MQ', '马提尼克岛', 'country', 'MQ', '马提尼克岛', '', NULL, 0, 0, '2024-07-03 17:28:24', '2024-07-03 17:28:24');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'MR', '毛里塔尼亚', 'country', 'MR', '毛里塔尼亚', '', NULL, 1, 0, '2024-07-03 17:28:24', '2024-07-03 17:28:24');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'MS', '蒙塞拉特岛', 'country', 'MS', '蒙塞拉特岛', '', NULL, 0, 0, '2024-07-03 17:28:24', '2024-07-03 17:28:24');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'MT', '马耳他', 'country', 'MT', '马耳他', '', NULL, 1, 0, '2024-07-03 17:28:24', '2024-07-03 17:28:24');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'MU', '毛里求斯', 'country', 'MU', '毛里求斯', '', NULL, 1, 0, '2024-07-03 17:28:25', '2024-07-03 17:28:25');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'MV', '马尔代夫', 'country', 'MV', '马尔代夫', '', NULL, 1, 0, '2024-07-03 17:28:25', '2024-07-03 17:28:25');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'MW', '马拉维', 'country', 'MW', '马拉维', '', NULL, 1, 0, '2024-07-03 17:28:25', '2024-07-03 17:28:25');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'MX', '墨西哥', 'country', 'MX', '墨西哥', '', NULL, 1, 1, '2024-07-03 17:28:25', '2024-07-03 17:28:25');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'MY', '马来西亚', 'country', 'MY', '马来西亚', '', NULL, 1, 1, '2024-07-03 17:28:25', '2024-07-03 17:28:25');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'MZ', '莫桑比克', 'country', 'MZ', '莫桑比克', '', NULL, 1, 0, '2024-07-03 17:28:25', '2024-07-03 17:28:25');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'NA', '纳米比亚', 'country', 'NA', '纳米比亚', '', NULL, 1, 0, '2024-07-03 17:28:25', '2024-07-03 17:28:25');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'NC', '新喀里多尼亚', 'country', 'NC', '新喀里多尼亚', '', NULL, 1, 0, '2024-07-03 17:28:25', '2024-07-03 17:28:25');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'NE', '尼日尔', 'country', 'NE', '尼日尔', '', NULL, 1, 0, '2024-07-03 17:28:25', '2024-07-03 17:28:25');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'NF', '诺福克岛', 'country', 'NF', '诺福克岛', '', NULL, 0, 0, '2024-07-03 17:28:25', '2024-07-03 17:28:25');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'NG', '尼日利亚', 'country', 'NG', '尼日利亚', '', NULL, 1, 1, '2024-07-03 17:28:25', '2024-07-03 17:28:25');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'NI', '尼加拉瓜', 'country', 'NI', '尼加拉瓜', '', NULL, 1, 1, '2024-07-03 17:28:25', '2024-07-03 17:28:25');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'NL', '荷兰', 'country', 'NL', '荷兰', '', NULL, 1, 1, '2024-07-03 17:28:25', '2024-07-03 17:28:25');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'NO', '挪威', 'country', 'NO', '挪威', '', NULL, 1, 1, '2024-07-03 17:28:25', '2024-07-03 17:28:25');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'NP', '尼泊尔', 'country', 'NP', '尼泊尔', '', NULL, 1, 0, '2024-07-03 17:28:26', '2024-07-03 17:28:26');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'NR', '瑙鲁', 'country', 'NR', '瑙鲁', '', NULL, 1, 0, '2024-07-03 17:28:26', '2024-07-03 17:28:26');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'NU', '纽埃', 'country', 'NU', '纽埃', '', NULL, 0, 0, '2024-07-03 17:28:26', '2024-07-03 17:28:26');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'NZ', '新西兰', 'country', 'NZ', '新西兰', '', NULL, 1, 1, '2024-07-03 17:28:26', '2024-07-03 17:28:26');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'OM', '阿曼', 'country', 'OM', '阿曼', '', NULL, 1, 0, '2024-07-03 17:28:26', '2024-07-03 17:28:26');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'PA', '巴拿马', 'country', 'PA', '巴拿马', '', NULL, 1, 1, '2024-07-03 17:28:26', '2024-07-03 17:28:26');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'PE', '秘鲁', 'country', 'PE', '秘鲁', '', NULL, 1, 1, '2024-07-03 17:28:26', '2024-07-03 17:28:26');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'PF', '法属玻利尼西亚', 'country', 'PF', '法属玻利尼西亚', '', NULL, 1, 0, '2024-07-03 17:28:26', '2024-07-03 17:28:26');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'PG', '巴布亚新几内亚', 'country', 'PG', '巴布亚新几内亚', '', NULL, 1, 0, '2024-07-03 17:28:26', '2024-07-03 17:28:26');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'PH', '菲律宾', 'country', 'PH', '菲律宾', '', NULL, 1, 1, '2024-07-03 17:28:26', '2024-07-03 17:28:26');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'PK', '巴基斯坦', 'country', 'PK', '巴基斯坦', '', NULL, 1, 0, '2024-07-03 17:28:26', '2024-07-03 17:28:26');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'PL', '波兰', 'country', 'PL', '波兰', '', NULL, 1, 1, '2024-07-03 17:28:26', '2024-07-03 17:28:26');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'PM', '圣皮埃尔和密克隆', 'country', 'PM', '圣皮埃尔和密克隆', '', NULL, 0, 0, '2024-07-03 17:28:26', '2024-07-03 17:28:26');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'PN', '皮特凯恩', 'country', 'PN', '皮特凯恩', '', NULL, 0, 0, '2024-07-03 17:28:26', '2024-07-03 17:28:26');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'PR', '波多黎各', 'country', 'PR', '波多黎各', '', NULL, 1, 1, '2024-07-03 17:28:27', '2024-07-03 17:28:27');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'PS', '巴勒斯坦', 'country', 'PS', '巴勒斯坦', '', NULL, 0, 0, '2024-07-03 17:28:27', '2024-07-03 17:28:27');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'PT', '葡萄牙', 'country', 'PT', '葡萄牙', '', NULL, 1, 1, '2024-07-03 17:28:27', '2024-07-03 17:28:27');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'PW', '帕劳', 'country', 'PW', '帕劳', '', NULL, 0, 0, '2024-07-03 17:28:27', '2024-07-03 17:28:27');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'PY', '巴拉圭', 'country', 'PY', '巴拉圭', '', NULL, 1, 1, '2024-07-03 17:28:27', '2024-07-03 17:28:27');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'QA', '卡塔尔', 'country', 'QA', '卡塔尔', '', NULL, 1, 0, '2024-07-03 17:28:27', '2024-07-03 17:28:27');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'RE', '留尼汪', 'country', 'RE', '留尼汪', '', NULL, 0, 0, '2024-07-03 17:28:27', '2024-07-03 17:28:27');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'RO', '罗马尼亚', 'country', 'RO', '罗马尼亚', '', NULL, 1, 1, '2024-07-03 17:28:27', '2024-07-03 17:28:27');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'RS', '塞尔维亚', 'country', 'RS', '塞尔维亚', '', NULL, 0, 1, '2024-07-03 17:28:27', '2024-07-03 17:28:27');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'RU', '俄罗斯', 'country', 'RU', '俄罗斯', '', NULL, 1, 1, '2024-07-03 17:28:27', '2024-07-03 17:28:27');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'RW', '卢旺达', 'country', 'RW', '卢旺达', '', NULL, 1, 0, '2024-07-03 17:28:27', '2024-07-03 17:28:27');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'SA', '沙特阿拉伯', 'country', 'SA', '沙特阿拉伯', '', NULL, 1, 1, '2024-07-03 17:28:27', '2024-07-03 17:28:27');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'SB', '所罗门群岛', 'country', 'SB', '所罗门群岛', '', NULL, 1, 0, '2024-07-03 17:28:27', '2024-07-03 17:28:27');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'SC', '塞舌尔', 'country', 'SC', '塞舌尔', '', NULL, 1, 0, '2024-07-03 17:28:28', '2024-07-03 17:28:28');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'SE', '瑞典', 'country', 'SE', '瑞典', '', NULL, 1, 1, '2024-07-03 17:28:28', '2024-07-03 17:28:28');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'SG', '新加坡', 'country', 'SG', '新加坡', '', NULL, 1, 0, '2024-07-03 17:28:28', '2024-07-03 17:28:28');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'SH', '圣赫勒拿', 'country', 'SH', '圣赫勒拿', '', NULL, 1, 0, '2024-07-03 17:28:28', '2024-07-03 17:28:28');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'SI', '斯洛文尼亚', 'country', 'SI', '斯洛文尼亚', '', NULL, 1, 0, '2024-07-03 17:28:28', '2024-07-03 17:28:28');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'SJ', '斯瓦尔巴群岛和扬马延岛', 'country', 'SJ', '斯瓦尔巴群岛和扬马延岛', '', NULL, 0, 0, '2024-07-03 17:28:28', '2024-07-03 17:28:28');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'SK', '斯洛伐克', 'country', 'SK', '斯洛伐克', '', NULL, 1, 0, '2024-07-03 17:28:28', '2024-07-03 17:28:28');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'SL', '塞拉利昂', 'country', 'SL', '塞拉利昂', '', NULL, 1, 0, '2024-07-03 17:28:28', '2024-07-03 17:28:28');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'SM', '圣马力诺', 'country', 'SM', '圣马力诺', '', NULL, 1, 0, '2024-07-03 17:28:28', '2024-07-03 17:28:28');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'SN', '塞内加尔', 'country', 'SN', '塞内加尔', '', NULL, 1, 0, '2024-07-03 17:28:28', '2024-07-03 17:28:28');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'SO', '索马里', 'country', 'SO', '索马里', '', NULL, 1, 0, '2024-07-03 17:28:28', '2024-07-03 17:28:28');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'SR', '苏里南', 'country', 'SR', '苏里南', '', NULL, 1, 0, '2024-07-03 17:28:28', '2024-07-03 17:28:28');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'SS', '南苏丹', 'country', 'SS', '南苏丹', '', NULL, 1, 0, '2024-07-03 17:28:29', '2024-07-03 17:28:29');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'ST', '圣多美和普林西比', 'country', 'ST', '圣多美和普林西比', '', NULL, 1, 0, '2024-07-03 17:28:29', '2024-07-03 17:28:29');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'SV', '萨尔瓦多', 'country', 'SV', '萨尔瓦多', '', NULL, 1, 1, '2024-07-03 17:28:29', '2024-07-03 17:28:29');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'SX', '荷属圣马丁', 'country', 'SX', '荷属圣马丁', '', NULL, 0, 0, '2024-07-03 17:28:29', '2024-07-03 17:28:29');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'SZ', '斯威士兰', 'country', 'SZ', '斯威士兰', '', NULL, 1, 0, '2024-07-03 17:28:29', '2024-07-03 17:28:29');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'TC', '特克斯和凯科斯群岛', 'country', 'TC', '特克斯和凯科斯群岛', '', NULL, 0, 0, '2024-07-03 17:28:29', '2024-07-03 17:28:29');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'TD', '乍得', 'country', 'TD', '乍得', '', NULL, 1, 0, '2024-07-03 17:28:29', '2024-07-03 17:28:29');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'TF', '法属南部领地', 'country', 'TF', '法属南部领地', '', NULL, 0, 0, '2024-07-03 17:28:29', '2024-07-03 17:28:29');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'TG', '多哥', 'country', 'TG', '多哥', '', NULL, 1, 0, '2024-07-03 17:28:29', '2024-07-03 17:28:29');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'TH', '泰国', 'country', 'TH', '泰国', '', NULL, 1, 1, '2024-07-03 17:28:29', '2024-07-03 17:28:29');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'TJ', '塔吉克斯坦', 'country', 'TJ', '塔吉克斯坦', '', NULL, 1, 0, '2024-07-03 17:28:29', '2024-07-03 17:28:29');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'TK', '托克劳', 'country', 'TK', '托克劳', '', NULL, 1, 0, '2024-07-03 17:28:30', '2024-07-03 17:28:30');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'TL', '东帝汶', 'country', 'TL', '东帝汶', '', NULL, 0, 0, '2024-07-03 17:28:30', '2024-07-03 17:28:30');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'TM', '土库曼斯坦', 'country', 'TM', '土库曼斯坦', '', NULL, 1, 0, '2024-07-03 17:28:30', '2024-07-03 17:28:30');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'TN', '突尼斯', 'country', 'TN', '突尼斯', '', NULL, 1, 0, '2024-07-03 17:28:30', '2024-07-03 17:28:30');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'TO', '汤加', 'country', 'TO', '汤加', '', NULL, 1, 0, '2024-07-03 17:28:30', '2024-07-03 17:28:30');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'TR', '土耳其', 'country', 'TR', '土耳其', '', NULL, 1, 1, '2024-07-03 17:28:30', '2024-07-03 17:28:30');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'TT', '特立尼达和多巴哥', 'country', 'TT', '特立尼达和多巴哥', '', NULL, 1, 0, '2024-07-03 17:28:30', '2024-07-03 17:28:30');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'TV', '图瓦卢', 'country', 'TV', '图瓦卢', '', NULL, 1, 0, '2024-07-03 17:28:30', '2024-07-03 17:28:30');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'TW', '台湾', 'country', 'TW', '台湾', '', NULL, 1, 1, '2024-07-03 17:28:30', '2024-07-03 17:28:30');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'TZ', '坦桑尼亚', 'country', 'TZ', '坦桑尼亚', '', NULL, 0, 0, '2024-07-03 17:28:30', '2024-07-03 17:28:30');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'UA', '乌克兰', 'country', 'UA', '乌克兰', '', NULL, 1, 1, '2024-07-03 17:28:30', '2024-07-03 17:28:30');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'UG', '乌干达', 'country', 'UG', '乌干达', '', NULL, 1, 0, '2024-07-03 17:28:30', '2024-07-03 17:28:30');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'UM', '美国本土外小岛屿', 'country', 'UM', '美国本土外小岛屿', '', NULL, 0, 0, '2024-07-03 17:28:30', '2024-07-03 17:28:30');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'US', '美国', 'country', 'US', '美国', '', NULL, 1, 1, '2024-07-03 17:28:31', '2024-07-03 17:28:31');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'UY', '乌拉圭', 'country', 'UY', '乌拉圭', '', NULL, 1, 1, '2024-07-03 17:28:31', '2024-07-03 17:28:31');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'UZ', '乌兹别克斯坦', 'country', 'UZ', '乌兹别克斯坦', '', NULL, 1, 0, '2024-07-03 17:28:31', '2024-07-03 17:28:31');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'VA', '梵蒂冈城', 'country', 'VA', '梵蒂冈城', '', NULL, 0, 0, '2024-07-03 17:28:31', '2024-07-03 17:28:31');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'VC', '圣文森特和格林纳丁斯', 'country', 'VC', '圣文森特和格林纳丁斯', '', NULL, 0, 0, '2024-07-03 17:28:31', '2024-07-03 17:28:31');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'VE', '委内瑞拉', 'country', 'VE', '委内瑞拉', '', NULL, 1, 1, '2024-07-03 17:28:31', '2024-07-03 17:28:31');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'VG', '英属维尔京群岛', 'country', 'VG', '英属维尔京群岛', '', NULL, 0, 0, '2024-07-03 17:28:31', '2024-07-03 17:28:31');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'VI', '美属维尔京群岛', 'country', 'VI', '美属维尔京群岛', '', NULL, 0, 0, '2024-07-03 17:28:31', '2024-07-03 17:28:31');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'VN', '越南', 'country', 'VN', '越南', '', NULL, 1, 1, '2024-07-03 17:28:31', '2024-07-03 17:28:31');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'VU', '瓦努阿图', 'country', 'VU', '瓦努阿图', '', NULL, 1, 0, '2024-07-03 17:28:31', '2024-07-03 17:28:31');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'WF', '瓦利斯和富图纳群岛', 'country', 'WF', '瓦利斯和富图纳群岛', '', NULL, 0, 0, '2024-07-03 17:28:31', '2024-07-03 17:28:31');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'WS', '萨摩亚', 'country', 'WS', '萨摩亚', '', NULL, 0, 0, '2024-07-03 17:28:31', '2024-07-03 17:28:31');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'XK', '科索沃', 'country', 'XK', '科索沃', '', NULL, 0, 0, '2024-07-03 17:28:31', '2024-07-03 17:28:31');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'YE', '也门', 'country', 'YE', '也门', '', NULL, 1, 0, '2024-07-03 17:28:32', '2024-07-03 17:28:32');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'YT', '马约特', 'country', 'YT', '马约特', '', NULL, 0, 0, '2024-07-03 17:28:32', '2024-07-03 17:28:32');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'ZA', '南非', 'country', 'ZA', '南非', '', NULL, 1, 1, '2024-07-03 17:28:32', '2024-07-03 17:28:32');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'ZM', '赞比亚', 'country', 'ZM', '赞比亚', '', NULL, 1, 0, '2024-07-03 17:28:32', '2024-07-03 17:28:32');
INSERT INTO fb_targeting_position (unique_key, name, type, country_code, country_name, region, region_id, supports_region, supports_city, created, updated) VALUES ( 'ZW', '津巴布韦', 'country', 'ZW', '津巴布韦', '', NULL, 1, 0, '2024-07-03 17:28:32', '2024-07-03 17:28:32');
