
-- 新增菜单
INSERT INTO `sys_menu` (`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (2036, '投放包配置', 1, 4, 'package-config', 'system/package-config/index', NULL, 1, 0, 'C', '0', '0', '', 'color', 'admin', '2024-03-18 16:56:31', 'admin', '2024-03-18 16:56:44', '');
INSERT INTO `sys_menu` (`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (2037, '修改', 2036, 1, '', NULL, NULL, 1, 0, 'F', '0', '0', 'system:package:edit', '#', 'admin', '2024-03-18 16:57:18', '', NULL, '');
INSERT INTO `sys_menu` (`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (2038, '新增', 2036, 2, '', NULL, NULL, 1, 0, 'F', '0', '0', 'system:package:add', '#', 'admin', '2024-03-18 16:57:38', '', NULL, '');
INSERT INTO `sys_menu` (`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (2039, '删除', 2036, 1, '', NULL, NULL, 1, 0, 'F', '0', '0', 'system:package:remove', '#', 'admin', '2024-03-18 16:57:57', '', NULL, '');
INSERT INTO `sys_menu` (`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (2040, '查询', 2036, 1, '', NULL, NULL, 1, 0, 'F', '0', '0', 'system:package:query', '#', 'admin', '2024-03-18 20:23:26', '', NULL, '');
INSERT INTO `sys_menu` (`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (2041, '导出', 2031, 1, '', NULL, NULL, 1, 0, 'F', '0', '0', 'system:roas:export', '#', 'admin', '2024-03-19 16:21:47', '', NULL, '');

-- 新增字典类型
INSERT INTO `sys_dict_type` (`dict_id`, `dict_name`, `dict_type`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (100, '通用数字是否', 'sys_common_yesno', '0', 'admin', '2024-03-04 17:55:50', '', NULL, NULL);
INSERT INTO `sys_dict_type` (`dict_id`, `dict_name`, `dict_type`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (101, '投放平台', 'sys_place_platform_type', '0', 'admin', '2024-03-18 18:10:31', '', NULL, NULL);

-- 新增字典数据
INSERT INTO `sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (200, 0, '是', '1', 'sys_common_yesno', NULL, 'primary', 'N', '0', 'admin', '2024-03-04 17:56:35', '', NULL, NULL);
INSERT INTO `sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (201, 0, '否', '0', 'sys_common_yesno', NULL, 'default', 'N', '0', 'admin', '2024-03-04 17:56:48', '', NULL, NULL);
INSERT INTO `sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (202, 0, 'Google', 'GG', 'sys_place_platform_type', NULL, 'primary', 'N', '0', 'admin', '2024-03-18 18:11:00', 'admin', '2024-03-18 19:54:41', NULL);
INSERT INTO `sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (203, 0, 'Feedback', 'FB', 'sys_place_platform_type', NULL, 'success', 'N', '0', 'admin', '2024-03-18 18:11:31', 'admin', '2024-03-18 19:54:36', NULL);
INSERT INTO `sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (204, 0, 'Organic', 'Organic', 'sys_place_platform_type', NULL, 'default', 'N', '0', 'admin', '2024-03-18 19:54:29', '', NULL, NULL);



