

INSERT INTO `sys_menu` (`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (2025, '权限配置', 1, 3, 'permissions', 'system/permissions/index', NULL, 1, 0, 'C', '0', '0', NULL, 'people', 'admin', '2024-02-28 15:06:17', '', NULL, '');
INSERT INTO `sys_menu` (`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (2026, '查询', 2025, 0, '', NULL, NULL, 1, 0, 'F', '0', '0', 'system:permissions:query', '#', 'admin', '2024-02-28 15:06:50', '', NULL, '');
INSERT INTO `sys_menu` (`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (2027, '新增', 2025, 1, '', NULL, NULL, 1, 0, 'F', '0', '0', 'system:permissions:add', '#', 'admin', '2024-02-28 15:07:13', '', NULL, '');
INSERT INTO `sys_menu` (`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (2028, '编辑', 2025, 2, '', NULL, NULL, 1, 0, 'F', '0', '0', 'system:permissions:edit', '#', 'admin', '2024-02-28 15:07:33', '', NULL, '');
INSERT INTO `sys_menu` (`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (2029, '删除', 2025, 4, '', NULL, NULL, 1, 0, 'F', '0', '0', 'system:permissions:remove', '#', 'admin', '2024-02-28 15:07:54', '', NULL, '');
INSERT INTO `sys_menu` (`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (2030, '投放数据', 0, 6, 'delivery-data', NULL, NULL, 1, 0, 'M', '0', '0', NULL, 'redis', 'admin', '2024-02-28 15:08:28', '', NULL, '');
INSERT INTO `sys_menu` (`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (2031, '同期群ROAS', 2030, 0, 'period-roas', 'delivery-data/same-period-roas/index', NULL, 1, 0, 'C', '0', '0', NULL, 'server', 'admin', '2024-02-28 15:09:06', '', NULL, '');
INSERT INTO `sys_menu` (`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (2032, '关键字管理', 1, 3, 'keyword-manage', 'system/keyword-manage/index', NULL, 1, 0, 'C', '0', '0', NULL, 'dict', 'admin', '2024-02-29 16:13:39', '', NULL, '');
INSERT INTO `sys_menu` (`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (2033, '查询', 2032, 0, '', NULL, NULL, 1, 0, 'F', '0', '0', 'system:keywords:query', '#', 'admin', '2024-02-29 16:14:29', '', NULL, '');
INSERT INTO `sys_menu` (`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (2034, '新增', 2032, 1, '', NULL, NULL, 1, 0, 'F', '0', '0', 'system:keywords:add', '#', 'admin', '2024-02-29 16:14:46', '', NULL, '');
INSERT INTO `sys_menu` (`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (2035, '编辑', 2032, 2, '', NULL, NULL, 1, 0, 'F', '0', '0', 'system:keywords:edit', '#', 'admin', '2024-02-29 16:15:01', '', NULL, '');
