CREATE TABLE currency_code
(
    id           SERIAL PRIMARY KEY,
    name         VARCHAR(64) NOT NULL COMMENT '货币名称',
    code         VARCHAR(8)  NOT NULL COMMENT '货币代码',
    offset_value INTEGER     NOT NULL COMMENT '偏移值',
    created_at   TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) COMMENT '货币代码表';

-- 唯一索引
ALTER TABLE currency_code
    ADD UNIQUE INDEX uni_p_id(code) USING BTREE;

-- 插入数据
INSERT INTO currency_code (name, code, offset_value)
VALUES ('阿尔及利亚第纳尔', 'DZD', 100),
       ('阿根廷比索', 'ARS', 100),
       ('澳大利亚元', 'AUD', 100),
       ('巴林第纳尔', 'BHD', 100),
       ('孟加拉塔卡', 'BDT', 100),
       ('玻利维亚币', 'BOB', 100),
       ('保加利亚列弗', 'BGN', 100),
       ('巴西雷亚尔', 'BRL', 100),
       ('英镑', 'GBP', 100),
       ('加拿大元', 'CAD', 100),
       ('智利比索', 'CLP', 1),
       ('人民币', 'CNY', 100),
       ('哥伦比亚比索', 'COP', 1),
       ('哥斯达黎加科朗', 'CRC', 1),
       ('克罗地亚库纳', 'HRK', 100),
       ('捷克克朗', 'CZK', 100),
       ('丹麦克朗', 'DKK', 100),
       ('埃及镑', 'EGP', 100),
       ('欧元', 'EUR', 100),
       ('危地马拉格查尔', 'GTQ', 100),
       ('洪都拉斯伦皮拉', 'HNL', 100),
       ('港元', 'HKD', 100),
       ('匈牙利福林', 'HUF', 1),
       ('冰岛克朗', 'ISK', 1),
       ('印度卢比', 'INR', 100),
       ('印尼盾', 'IDR', 1),
       ('以色列新谢克尔', 'ILS', 100),
       ('日元', 'JPY', 1),
       ('约旦第纳尔', 'JOD', 100),
       ('肯尼亚先令', 'KES', 100),
       ('韩元', 'KRW', 1),
       ('拉脱维亚拉特', 'LVL', 100),
       ('立陶宛立特', 'LTL', 100),
       ('澳门元', 'MOP', 100),
       ('马来西亚令吉', 'MYR', 100),
       ('墨西哥比索', 'MXN', 100),
       ('新西兰元', 'NZD', 100),
       ('尼加拉瓜科多巴', 'NIO', 100),
       ('尼日利亚奈拉', 'NGN', 100),
       ('挪威克郎', 'NOK', 100),
       ('巴基斯坦卢比', 'PKR', 100),
       ('巴拉圭瓜拉尼', 'PYG', 1),
       ('秘鲁新索尔', 'PEN', 100),
       ('菲律宾比索', 'PHP', 100),
       ('波兰兹罗提', 'PLN', 100),
       ('卡塔尔里亚尔', 'QAR', 100),
       ('罗马尼亚列伊', 'RON', 100),
       ('俄罗斯卢布', 'RUB', 100),
       ('沙特里亚尔', 'SAR', 100),
       ('塞尔维亚第纳尔', 'RSD', 100),
       ('新加坡元', 'SGD', 100),
       ('斯洛伐克克朗', 'SKK', 100),
       ('南非兰特', 'ZAR', 100),
       ('瑞典克朗', 'SEK', 100),
       ('瑞士法郎', 'CHF', 100),
       ('台币', 'TWD', 1),
       ('泰铢', 'THB', 100),
       ('土耳其里拉', 'TRY', 100),
       ('阿联酋迪拉姆', 'AED', 100),
       ('乌克兰格里夫纳', 'UAH', 100),
       ('美元', 'USD', 100),
       ('乌拉圭比索', 'UYU', 100),
       ('委内瑞拉玻利瓦尔', 'VEF', 100),
       ('越南盾', 'VND', 1),
       ('Facebook币', 'FBZ', 100),
       ('玻利瓦尔索巴拉诺', 'VES', 100);